apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-backend-deployment
  labels:
    app: form-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: form-backend
  template:
    metadata:
      labels:   
        app: form-backend
    spec:
      containers:
      - name: form-backend
        image: depaulacr.azurecr.io/form-backend:latest
        ports:
        - containerPort: 5000
